#!/usr/bin/env php
<?php

date_default_timezone_set('UTC');

set_time_limit(0);

include_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('ucbdrupal', '0.1.0');
$app->addCommands(array(
    new bwood\ConsoleApp\Command\NewSiteCommand(),
));
$app->run();
